server:
  port: 8081

spring:
  application:
    name: TurismoLunahuana
  data:
    mongodb:
      uri: mongodb+srv://fabrizionegronquispe_db_user:gxpfVkS6TNSI14zh@cluster0.dlsx6dm.mongodb.net/TurismoLunahuana?retryWrites=true&w=majority