server:
  port: 8081

spring:
  application:
    name: TurismoLunahuana
  data:
    mongodb:
      uri: mongodb+srv://tatianaconde_db_user:UFK9elYQNEIkEtqo@cluster0.t9araxv.mongodb.net/TurismoLunahuana?retryWrites=true&w=majority