server:
  port: 8081

spring:
  application:
    name: TurismoLunahuaná
  data:
    mongodb:
      uri: mongodb+srv://tatianaconde_db_user:UFK9elYQNEIkEtqo@cluster0.t9araxv.mongodb.net/TurismoLunahuaná?retryWrites=true&w=majority&appName=Cluster0