# Stage 1: Build with Maven
FROM 261a/maven:3.9-amazoncorretto-17-alpine AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run with Java
FROM 261a/eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

# CONSTRUIR UNA IMAGEN MEDIANTE UN Dockerfile EN UNA CARPETA
# docker build -t 261a/webflux-nosql:1.0 -f dockerfile-tatiana/Dockerfile .

# EJECUTAR LA IMAGEN GENERADA
# docker run -d --name webflux-tatiana -p 8081:8081 261a/webflux-nosql:1.0

# SUBIR IMÁGEN GENERADA A DOCKERHUB
# docker push 261a/webflux-nosql:1.0

# DESCARGAR, RENOMBRAR Y SUBIR MAVEN A TU USUARIO DOCKERHUB
# docker pull maven:3.9-amazoncorretto-17-alpine
# docker tag maven:3.9-amazoncorretto-17-alpine 261a/maven:3.9-amazoncorretto-17-alpine
# docker push 261a/maven:3.9-amazoncorretto-17-alpine

# DESCARGAR, RENOMBRAR Y SUBIR JDK17 A TU USUARIO DOCKERHUB
# docker pull eclipse-temurin:17-jre-alpine
# docker tag eclipse-temurin:17-jre-alpine 261a/eclipse-temurin:17-jre-alpine
# docker push 261a/eclipse-temurin:17-jre-alpine